### ISSUE TITLE
Добавление в страницу личного кабинета фильтрацию мероприятий

### ISSUE THREAD

**Issue by ikhmat** [painprog/LetsGo#19]
- добавить фильтрацию мероприятий
- фильтрация должна быть по:
> -  по категории мероприятия
> - по статусу мероприятия
> - по дате от и до
- блок с фильтрацией скрыт, при нажатии на кнопку "фильрация", показывается это блок

ожидаемое время: 4 часа

**Comment by ivanrocafella** [comment]
![image](https://user-images.githubusercontent.com/88390642/145001057-42b74624-37de-4a58-abc3-bb66b6fdae90.png)
Затрачено: 4 часа
