### ISSUE TITLE
Календарь на главной странице

### ISSUE THREAD

**Issue by Anastasia799** [painprog/LetsGo#24]
- Добавить календарь на главной странице.
- При выборе определенной даты , появляется кнопка для перехода на страницу со всеми событиями, которые  назначены на эту дату.
![image](https://user-images.githubusercontent.com/88529142/145213480-0b1b4426-3e33-4ab0-9648-e02167ac8076.png)
![image](https://user-images.githubusercontent.com/88529142/145213671-bb6df450-8033-4cd6-b59a-3cdf2a307d6d.png)
Планируемое время: 4 часа

**Comment by painprog** [comment]
source: https://github.com/trananhtuat/js-calendar

**Comment by painprog** [comment]
Затрачено: 10 ч.
