### ISSUE TITLE
Изменение базы данных

### ISSUE THREAD

**Issue by Anastasia799** [painprog/LetsGo#32]
- поле для фотографии площадки
- Добавить поле string TicketIdentified
- У категорий добавить поле ParentId
- С помощью Data Seeding добавить площадки мероприятий
- Сделать enum для для того, чтобы отличать категории имеющие parentId и не имеющие
- Использовать HasData для Data Seed 
- Создать json файл с нужными объектами, которые будут десериализоваться в HasData

Планируемое время: 4 часа

**Comment by corianderr** [comment]
Затрачено: 4 часа
