### ISSUE TITLE
Добавление карты на детальной станице событий

### ISSUE THREAD

**Issue by Anastasia799** [painprog/LetsGo#33]
- Добавить карту  на детальной станице событий, для отображения местоположения места проведения данного события.

![image](https://user-images.githubusercontent.com/88529142/145214068-972b4025-63da-4771-8c9e-c7c469f30b72.png)

**Comment by ikhmat** [comment]
затрачено: 4 часа

**Comment by ikhmat** [comment]
затрачено: 4 часа
