### ISSUE TITLE
Рефакторинг фильтрации в личном кабинете

### ISSUE THREAD

**Issue by Anastasia799** [painprog/LetsGo#34]
- Поместить фильтрацию в отдельный блок, вместо Pop-up 
- Вместо радиокнопок нужно поставить checkbox 
- Добавить возможность фильтрации по подкатегориям

**Comment by ivanrocafella** [comment]
Блок с фильтрами оставил скрытым, но теперь он отображается и скрывается по нажатию на кнопку "Фильтрация"
![image](https://user-images.githubusercontent.com/88390642/145712841-b2e784e9-ed26-444f-89ba-ac6d8b5248fd.png)
Затрачено: 4 часа
