### ISSUE TITLE
Добавление сортировки мероприятий в личный кабинет

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#36]
**Требования:**
1. Сортировка должна производится по следующим критериям: 

> -  название мероприятия
> -  минимальная стоимость билета 
> -  дата начала

2. Разместить над блоком с фильтрацией как показано на рисунке ниже
![image](https://user-images.githubusercontent.com/88390642/146168135-f5e398e2-13d4-4b70-9ce1-394c2641878f.png)

**Критерии приема:**
Список мероприятий после первичной загрузки страницы уже отсортирован по дате начала от самой ближайшей к наиболее удаленной. Выбор критерия сортировки производится через клик на одну из трех ссылок. Порядок сортировки по уже выбранному критерию меняется через повторный клик по ссылке 

**Планируемое время: 9 часов**

**Comment by corianderr** [comment]
Затрачено: 3 часа
