### ISSUE TITLE
Добавить фильтрацию мероприятий на главную страницу

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#37]
**Требования:**

> 1. Функционал идентичен функционалу фильтрации в личном кабинете
> 2. Блок с фильтрацией статичен и расположен справа от контента с мероприятиями (пример на рисунке ниже)

![image](https://user-images.githubusercontent.com/88390642/146158519-d1d08937-0346-46ce-951c-d1ab14144b50.png)

**Критерии приема:**
Пользователь нажимает на кнопку "Фильтры", страница прокручивается до блока с фильтрами. В блоке с фильтрами выбирается один или несколько из них, нажимает "Показать" и в блоке контента выходят мероприятия, соответствующие выбранным фильтрам 

**Планируемое время: 3 часа**

**Comment by ikhmat** [comment]
затрачено: 8-12 часов (потерял счет времени)
