### ISSUE TITLE
Рефакторинг личного кабинета

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#38]
**Исправления и изменения:**

- Устранить нежелательную переадресацию при нажатии на кнопки внутри карточки с мероприятием на её детальную страницу
- Исправить описание статуса (заменить мужской род на средний, например: "ОпубликованО" вместо "Опубликован")
- Рефакторинг сервиса 

**Планируемое время: 3 часа**

P.S. Устранять любимые неполадки, найденные во время работы, и фиксировать время, затраченное на них, как "дополнительное"

**Comment by ikhmat** [comment]
- дополнительное 2 часа на рефакторинг сервисов

**Comment by ikhmat** [comment]
затрачено: 5 часов
