### ISSUE TITLE
Рефакторинг аутентификации пользователя на сайте 

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#40]
**Требования:**

> 1. Добавить валидацию на несуществующий логин или email пользователя при входе на сайт

> 2. Добавить валидацию на несуществующий email пользователя во view "ResetPassword"

> 3. Удалить блок кода, который условно закомментирован на рисунке ниже

![Лишний блок кода](https://user-images.githubusercontent.com/88390642/146341558-0e221cc1-6331-4424-8202-cefdc5089f15.png)

> 4. Настроить сообщения ошибок валидации во view "ResetPassword", к примеру, ошибки о неправильном токене (см. рис)

![токен](https://user-images.githubusercontent.com/88390642/146341977-7bb1d037-4c67-40c0-8577-e42ff0a5b421.png)

**Критерии приема:**
Не должно вылетать исключение, если были введены логин или почта юзера, которого нет в базе. На странице восстановления пароля инпут для почты не должен принимать почту отсутствующего в базе данных юзера. Вместо ошибки валидации "Invalid token" пусть отображается "Это не ваш почтовый адрес"

**Планируемое время: 4 часа**

**Comment by painprog** [comment]
Затрачено: 2.30 ч.
