### ISSUE TITLE
Страница редактирования профиля

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#41]
**Требования:**

> Функционал редактирования профиля по полям: Username, PhoneNumber, Avatar
> Настроить валидацию на всех полях ввода

**Критерии приема:**
На странице личного кабинета в карточке профиля есть кнопка "изменить", при клике на которую пользователя переносит на страницу редактирования профиля. Страница редактирования выполнена в стиле страницы добавления нового организатора. Валидация работает и отображает понятные сообщения (на русском)
**Планируемое время: 5 часов**

**Comment by ikhmat** [comment]
затрачено:
@Anastasia799 - 3 часа
@ikhmat - 2.5 часа
