### ISSUE TITLE
Локализация содержимого сайта часть 2

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#43]
**Требования:**

> - локализация должна быть выполнена на трёх языках: "русский", "English", "кыргызча"
> - локализовать представления содержащиеся в папках "Home", "Locations"

**Критерии приема:**
Представления в указанных папках должны быть доступны на трех языках. Предпочтительней внедрять ресурсные файлы непосредственно во view через внедрение зависимостей
**Планируемое время: 7 часов**

**Comment by corianderr** [comment]
Затрачено: 7 часов
