### ISSUE TITLE
Переключатель языка локализации

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#44]
**Требования:**

> - добавить переключатель трех языков "русский", "English", "кыргызча"
> - переключатель выполнить в виде флагов стран (пример см.рис)
![post-1-0-25564500-1410222955_thumb](https://user-images.githubusercontent.com/88390642/147045439-e0533cd1-411b-45b3-adc4-4e6db759db56.png)

**Критерии приема:**
При клике на один из трех флагов содержимое всей страницы переводится на язык страны, указанный на флаге
**Планируемое время: 4 часа**

**Comment by corianderr** [comment]
Затрачено 5 часов
