### ISSUE TITLE
Внесение изменений в базу данных, рефакторинг проекта

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#46]
**Требования:**

> - Добавить роль для пользователя, проверяющего статус билета и меняющего статус "не использован" на "использован"
> - Поменять в коде путь к папкам с файлами картинок

**Критерии приема:**
В базе должна появится ещё одна роль , назвать её можно на ваше усмотрение, главное чтобы подходила по смыслу к функциям, которые ей доступны. Аватарка профиля пользователя в представлениях не должна быть пустой.
**Планируемое время: 2 часа**

**Comment by painprog** [comment]
Затрачено: 1:40 ч.
