### ISSUE TITLE
Дополнительный функционал для фильтрации 

### ISSUE THREAD

**Issue by ivanrocafella** [painprog/LetsGo#47]
**Требования:**

> - Добавить отображение ранее выбранных критериев фильтрации 
> - Добавить сброс фильтров

**Критерии приема:**
После того, как пользователь отфильтровал список мероприятий и страница перезагрузилась, все выбранные им ранее критерии фильтрации должны быть отмечены (галочки в чекбоксах, выбранный статус в выпадающем списке и даты). Процесс сброса фильтров заключается в том, что после фильтрации в блоке с фильтрами рядом с кнопкой "показать" появляется кнопка "сбросить", после нажатия на которую  все поля ввода критериев фильтрации очищаются и отображается полный список мероприятий (см. рис.)
<img width="1280" alt="тикет" src="https://user-images.githubusercontent.com/88390642/147380206-0c441e87-88b3-43e8-bd20-d4c5d6be83fd.png">

**Планируемое время: 4 часа**

P.S. К этому таску приступить не ранее merge 39 ветки в мастер

**Comment by ikhmat** [comment]
затрачено: 5:25 минут
- была переделана передача категорий во фронт и их отображение
