### ISSUE TITLE
Рефакторинг отправки билетов

### ISSUE THREAD

**Issue by painprog** [painprog/LetsGo#48]
Необходимо изменить отправку билетов так что бы при отправке **n** билетов происходило **n** подключений и отключений, т.е. сейчас в цикле идёт подключение и отключение каждый раз внутри цикла.   
(добавить в сервис (emailservice) метод получающий список  билетов и отправляющий на почту эти билеты с 1 коннекор и дисконнектом)

**Comment by ikhmat** [comment]
затрачено: 4 часа
