### ISSUE TITLE
Создание контроллера для API

### ISSUE THREAD

**Issue by painprog** [painprog/LetsGo#49]
Необходимо создать контроллер для будущей API для контроля входа посетителей по электронным билетам. Данный контроллер должен обрабатывать 3 GET запроса:

1. Проверить статус
При вызове данной функции, в приложении открывается камера и при наведении на QR-код электронного билета происходит запрос в бд о получении статуса данного билета(использован/не использован), который будет выведен на экране приложения. 
(Данный функционал будет разработан на мобилке, все что ниже необходимо реализовать на бэкэнде)

2. Прошёл
Данная функция будет доступна для вызова на экране приложения после вызова функции “проверить статус” при условии, если статус электронного билета будет “не использован”. При вызове функции “прошёл” в базе данных произойдет смена статуса по данному электронному билету с “не использован” на “использован” и при повторном сканировании этого билета система должна отобразить статус.

3. Откатить
Данная функция будет доступна для вызова на экране приложения после вызова функции “проверить статус” при условии, если статус электронного билета будет “использован”. При вызове функции “Откатить” в базе данных произойдет смена статуса по данному электронному билету с “использован” на “не использован”. Данная функция будет доступна только для пользователей типа “Developer” и “Director”.

**Comment by ChiBiz2z** [comment]
### Проверка статуса
![image](https://user-images.githubusercontent.com/88432358/148508498-ea868f4d-ca67-4644-a7f4-9093d7340f0f.png)

### Проверка изменения статуса на "Проверено"
![image](https://user-images.githubusercontent.com/88432358/148508541-384c8174-f75c-4091-839d-5651a1bd4bb2.png)
![image](https://user-images.githubusercontent.com/88432358/148508709-23c61605-c539-4d30-855d-e43c8634649b.png)

### Проверка отката статуса
![image](https://user-images.githubusercontent.com/88432358/148508580-07640d85-9976-4c71-94f9-bbde14a07188.png)

**Comment by ChiBiz2z** [comment]
Затраченное время 2 часа
