### ISSUE TITLE
Страница с QR кодом в PDF

### ISSUE THREAD

**Issue by ChiBiz2z** [painprog/LetsGo#53]
Необходимо провести ресерч по библиотекам по созданию PDF файлов. В случае если получится создать нормальный PDF файл, сообщить аналитику, приложить скриншоты, демонстрирующие корректность работы библиотеки.

**Comment by corianderr** [comment]
![53_1](https://user-images.githubusercontent.com/88391609/150628587-a300e5d6-6e39-4dfe-8652-62bfe08abf96.png)
![53_2](https://user-images.githubusercontent.com/88391609/150628588-337dd9a6-c6ce-4145-a69d-c6e5efe9ea62.png)

**Comment by corianderr** [comment]
Затрачено: 3.5 часа
