### ISSUE TITLE
Исправление поломанной вёрстки

### ISSUE THREAD

**Issue by ChiBiz2z** [painprog/LetsGo#54]
**- Необходимо исправить хэдер, ломающийся на маленьких экранах.**
После добавления локализации, нарушилась работа некоторого js кода
![image](https://user-images.githubusercontent.com/88432358/149912324-9b341646-ca7e-4e85-ad21-fd72458997be.png)
![image](https://user-images.githubusercontent.com/88432358/149912356-fa4f58cd-187c-4ad9-a047-80c135803ab8.png)

**- Сделать отступы для заголовков на странице личного кабинета.**
**- Исправить поломанные отображения фотографий, если такие будут замечены.**
**-Добавить адаптивное расположение кнопок на главной странице и на странице ЛК .**

При нахождении иных спорных моментов, касательно внешней оболочки сайта, сообщить аналитику лично. Тикет в таком случае будет обновлён.

Ожидаемое время: 5 часов.

**Comment by painprog** [comment]
Затрачено: 4.30 ч.
