### ISSUE TITLE
Переделывание регистрации организаторов.

### ISSUE THREAD

**Issue by ChiBiz2z** [painprog/LetsGo#56]
### Задумка:
Организатор по прежнему регистрируется по старой странице. Добавляется запись в БД. Затем администратор в своём ЛК имеет список регистрируемых и решает одобрять их или нет. После одобрения организатору приходит письмо с подтверждением почты. Подтвердив почту, он сможет заходить в свой ЛК. В случае отказа должно приходить письмо с уведомлением об отказе, запись с соответствующим организатором удаляется.

### Сделать:
- Для начала убрать кнопку входа в хэдере. Перенести её в боковую панель. 
- Создать поле "о себе" в модели организатора. Сделать возможность заполнения поля на странице регистрации.
- Создать внешний вид страницы со списком пользователей. Должна быть таблица с тремя колонками: почта, роль/о себе, функционал.

Колонка с функционалом должна содержать кнопки принятия и отказа для неподтвержденных организаторов. Редактирование и удаление для уже существующих организаторов и администраторов.

**Ожидаемое время**: 8 часов.

**Comment by painprog** [comment]
Затрачено: 9.30 часов.
![screenshot-localhost_44377-2022 01 24-15_47_03](https://user-images.githubusercontent.com/75982753/150760290-9f32b375-dc73-4b94-a651-02e157bc22b5.png)
