### ISSUE TITLE
Логика взаимодействия с User'ами.

### ISSUE THREAD

**Issue by ChiBiz2z** [painprog/LetsGo#57]
### Задумка:
Организатор по прежнему регистрируется по старой странице. Добавляется запись в БД. Затем администратор в своём ЛК имеет список регистрируемых и решает одобрять их или нет. После одобрения организатору приходит письмо с подтверждением почты. Подтвердив почту, он сможет заходить в свой ЛК. В случае отказа должно приходить письмо с уведомлением об отказе, запись с соответствующим организатором удаляется.

### Выполнить:
-Создать метод для удаления организиторов/администраторов из бд.
-Реализовать отправку почты после нажатия на одну из кнопок функционала таблицы организатора (issue #56).
-Добавить чекбоксы (приняты/запросы) для удобного отображения списков пользователей на странице со списком пользователями. 

**Ожидаемое время**: 6 часов.

**Comment by corianderr** [comment]
Затрачено: 9 часов
