### ISSUE TITLE
Исправление найденных неисправностей

### ISSUE THREAD

**Issue by ChiBiz2z** [painprog/LetsGo#60]
Подробное описание со скринами некоторых недочётов приведено в комментарии к тикету #58.
### Исправить
- Ограничить редактирование почты во всех личных кабинетах (либо убрать вовсе).
- Создание валидации почты на странице регистрации.
- Сделать клиентский функционал доступным для незарегистрированных пользователей (убрать/присвоить атрибуты ролей внутри контроллеров). 

- Исправление приплюснутой вёрстки в ЛК организатора.
- Удаление повторяющихся сообщений о валидации наверху страницы (создания, редактирования).
- Изменить порядок отображения или добавить сортировку мероприятий внутри ЛК админа. Принятые/Отказанные мероприятия находятся в начале списка, что не удобно. Как минимум должно быть отображение по новизне.

**Ожидаемое время:** 8 часов.

**Comment by ikhmat** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/58109318/151401425-d2bc515a-dce5-4384-a845-7f409a70eb33.png">
- исправить
